language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: game-clicker
  api_key:
    secure: s6GLHAkCt62XL9PcVF0ylxwU95VGGEJTc7v5vpO47lkrpbJFpDb2H2cqfeviT9tmC/wNM1JZ+xeK5qRu5kTMPNu+xtwYfLKiZUDwwYzjxSlTsn+gvPC2ObAuhSsAa9bN4aSVy812ITITQ8D4voUvKSDdDogK5cyvD5eaq6MU5W8LK77qqZbKrAJTMuJXLf79NqLkmMZpw1v+fIcrzaC1fLzMlxTEN7+4VEBQA6wU4uSFZQR7SVOtuca0c7WOYtA6NUSMzi//LwIlrYMNDBceU/SJ4DNVmAoEM6UNcW26BlSMSTshPaSJb8MY48hLNzdL0onjeILhe2gEcwPAGqCPmDh6wSOMnDLv1nejEpqDSxANUr/olZH2+uyyDFGW+GCaEuR4Ad3e3nIl5QH1hdnHCCIUrqZU7+q01PoDM4Xl1MSAu+PypF3vcLbaLkMpoXkDrkEMjezOl6x5e5AaTp5YMyR7lwJHFOwmP4se4T9/hrIJICj2LKigss6e9dyrUW9lps6w3dEYe9KObknmbAB6GTGvIb/fi074BjZHVrhmh6oUmDrzQ6h+Ssahh1rIufTXxLGNmVa0AMjb1zkq4x0XB2PBf4SYuxsk+B96gQAOKxbEn8MpViX2YoiUETvKEruq4P0aVqbXc7fJVU2jMsmDCXO2VSPXFSDcE2CUqcZWkWY=
